window.RENIDY_FUNERALS_CONFIG = {
  siteDomain: "renidyfunerals.com",
  funnelVariant: "renidyfunerals_standalone",
  defaultCtaUrl: "https://renidyfunerals.com/need-help-now/?intent=now",
  leadEndpoint: "",
  bookingUrl: "",
  ga4Id: "",
  gtmId: "",
  posthogToken: "",
  posthogHost: "https://us.i.posthog.com",
  tawkPropertyId: "",
  tawkWidgetId: "default",
  abEnabled: true,
  abExperimentId: "role_term_v1",
};
